name: example
description: example for Liquidity Gallery
version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  search_choices: ^2.0.3
  dropdown_search: ^5.0.6
  searchfield: ^0.8.2
  flutter_typeahead: ^4.3.8

  liquidity_gallery:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/pdf/MDO_example.pdf
