name: liquidity_gallery
description: A gallery for ellie & logistized app
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  another_flushbar: ^1.10.24
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.1
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.1.0
  calendar_timeline: ^1.0.1-null-safety.0
  carousel_slider: any
  cloud_firestore: any
  date_time_picker: ^2.1.0
  firebase_auth: any
  firebase_core: any
  firebase_storage: any
  fluent_ui: ^3.5.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  flutter_datetime_picker: any
  flutter_signin_button: ^2.0.0
  geocoding: ^2.0.0
  google_fonts: any
  google_sign_in: ^5.0.5
  image_picker: ^0.8.2
  intl: any
  location: ^4.3.0
  modal_bottom_sheet: ^2.0.0
  pdf_text: ^0.5.0
  share_plus: any
  url_launcher: ^6.0.9
  charts_flutter: ^0.12.0
  fluttertoast: ^8.0.9
  audioplayers: ^0.20.1
  honeywell_scanner: ^3.2.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: 
  assets:
    - assets/audios/
