name: liquidity_gallery
description: A gallery for ellie & logistized app
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  date_time_picker: ^2.0.0 #https://pub.dev/packages/date_time_picker

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
