name: liquidity_gallery
description: A gallery for ellie & logistized app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  another_flushbar: ^1.10.24
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^3.0.2
  bubble_tab_indicator: ^0.1.6
  cached_network_image: ^3.1.0
  calendar_timeline: ^1.0.1-null-safety.0
  carousel_slider: any
  cloud_firestore: any
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.1.2
  fluttertoast: ^8.0.9
  geocoding: ^2.0.0
  google_sign_in: ^6.0.2
  honeywell_scanner: ^4.0.0+14
  image_picker: ^0.8.2
  just_audio: ^0.9.25
  mobile_scanner: ^3.0.0
  string_similarity: ^2.0.0
  url_launcher: ^6.0.9
  dio: ^5.0.1
  intl: ^0.18.0
  share_plus: ^7.0.0
  google_fonts: ^4.0.4
  firebase_storage: ^11.1.2
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/audios/
